version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend-server-c
    ports:
      - '4001:4001'
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build: ./frontend
    container_name: frontend-c
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/react-app
      - /react-app/node_modules
    stdin_open: true
    tty : true